### PR TITLE
Remove qt4 support

### PR DESCRIPTION
**Pull request by neochapay**

### CODE REVIEW

**Comment by chriadam** [comment]
LGTM, thanks.  I will check to see if we have an internal bug we can use to tag this one with, to pass CI.

**Comment by chriadam** [comment]
I have created JB#54973 for this, can you please update the commit message with "Contributes to JB#54973"?  Thanks!

**Comment by neochapay** [comment]
> I have created JB#54973 for this, can you please update the commit message with "Contributes to JB#54973"? Thanks!

ready

**Comment by pvuorela** [comment]
I don't think we've used this module in years but since the changes are simple no objections either. I'll just merge, but then check if the whole thing could be moved to attic.

**Pull request merged**
